fullnameOverride: efs-pvc-exporter

replicaCount: 1

profile: default

namespace: development

image:
  repository: docker-registry.127.0.0.1.nip.io:30500/efs-pvc-exporter
  tag: latest
  pullPolicy: Always

labels: {}
annotations: {}

pod:
  labels: {}
  annotations: {}

pdb: {}

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 9002
  annotations: {}
  labels: {}

ingress:
  enabled: true
  subdomain: efs-pvc-exporter
  basedomain: 127.0.0.1.nip.io
  hosts: {}
  # hosts:
  #   - efs-pvc-exporter.opsnow.com
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  labels: {}

autoscaling:
  enabled: true
  min: 1
  max: 1
  cpu: 80
  mem: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 120m
    memory: 153Mi

    #readinessProbe:
        #  httpGet:
          #    path: /
    #    port: 3000
    #  initialDelaySeconds: 3
  #  periodSeconds: 10
  #  failureThreshold: 3

  #livenessProbe:
        #  httpGet:
          #    path: /
    #    port: 3000
    #  initialDelaySeconds: 3
  #  periodSeconds: 10
  #  failureThreshold: 3

# livenessProbe:
#   exec:
#     command:
#     - cat
#     - /tmp/healthy
#   initialDelaySeconds: 3
#   periodSeconds: 10
# livenessProbe:
#   tcpSocket:
#     port: 3000
#   initialDelaySeconds: 3
#   periodSeconds: 10

# hostNetwork: true
# dnsPolicy: Default

nodeSelector: {}

tolerations: []

affinity: {}

env: {}
  # - name: MESSAGE
  #   value: "hello world"

configmap:
  enabled: false
  data: {}
    # MESSAGE: "hello world"

secret:
  enabled: false
  data: {}
    # SECRET: c2VjcmV0IHdvcmxkCg==
