apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: batch
  name: {{ include "fullname" . }}
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims", "pods"]
  verbs: ["get", "list"]
