#
# CircleCI 2.0
#
version: 2
jobs:
  package:
    docker:
      - image: circleci/python
    working_directory: ~/works
    steps:
      - checkout
      - run:
          name: Package
          command: |
            mkdir target
            curl -sLo target/builder.sh repo.opsnow.io/valve-ctl/builder
            bash ./target/builder.sh package
            bash ./build.sh
      - persist_to_workspace:
          root: ~/works
          paths:
            - target
  publish:
    docker:
      - image: opspresso/awscli
    working_directory: ~/works
    steps:
      - attach_workspace:
          at: ~/works
      - run:
          name: Publish
          command: |
            bash ./target/builder.sh publish
  release:
    docker:
      - image: circleci/golang
    working_directory: ~/works
    steps:
      - attach_workspace:
          at: ~/works
      - run:
          name: Release
          command: |
            bash ./target/builder.sh release

workflows:
  version: 2
  apply:
    jobs:
      - package
      - publish:
          requires:
            - package
      - release:
          requires:
            - package
