image:
  repository: opsnowtools/efs-pvc-exporter
  tag: v0.0.0

schedule: "*/10 * * * *"

restart: Never

#resources:
#  requests:
#    cpu: 100m
#    memory: 128Mi
#  limits:
#    cpu: 120m
#    memory: 153Mi

env: {}

configmap:
  enabled: false

secret:
  enabled: false
